#!/bin/sh
# A login prompt on the serial console (ttyS0), matching the kernel
# cmdline's console=ttyS0,115200. A respawn entry, same as rc.d/getty - see
# that script's own comment.
NAME=getty-serial
CMD=/sbin/getty
ARGS="-L 115200 ttyS0"
BACKGROUND=no
. /etc/scraplinux/svc.lib
svc_main "$@"
