#!/bin/sh
NAME=sshd
CMD=/usr/bin/sshd
ARGS=""
BACKGROUND=no
PRESTART="mkdir -p /run/sshd; [ -f /etc/ssh/ssh_host_ed25519_key ] || ssh-keygen -A >/dev/null 2>&1"
. /etc/scraplinux/svc.lib
svc_main "$@"
