#!/bin/sh
PATH=/usr/bin
swapon -a
if [ -f /etc/scraplinux/zram.conf ]; then
	. /etc/scraplinux/zram.conf
	if [ -b /dev/zram0 ] || modprobe zram; then
		echo "${ZRAM_ALGO:-zstd}" >/sys/block/zram0/comp_algorithm
		echo "${ZRAM_SIZE:-4G}" >/sys/block/zram0/disksize
		mkswap /dev/zram0 >/dev/null && swapon -p 100 /dev/zram0
	fi
fi
exit 0
